name: Heroku CI/CD

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn test
    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku-api-key: $HEROKU_APP
                  heroku-app-name: $HEROKU_API_KEY
                  heroku-email: $HEROKU_EMAIL
